name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
 name: Running tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
        - name: Check coverage change from README 📫
        run: node bin/set-gh-status --check-against-readme  
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      PORT: ${{ secrets.PORT }}
      DB_TESTING_URL: ${{ secrets.DB_TESTING_URL }}


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm install -f
    - name: Test
      run: npm test

    
